version: '3'

services:
 angular:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-build
    restart: unless-stopped
    volumes:
     - C:\Users\Ebrahim\Desktop\jenkins\workspace\angular-pipeline:/usr/src/app
   