version: '3'

services:
 angular:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
     - /var/jenkins_home/workspace/angular-pipeline:/usr/src/app
    ports:
      - "4200:4200"