version: '3'

services:
 angular:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-build
    restart: unless-stopped
    volumes:
     - angular-volume:/usr/src/app
