version: '3'

services:
 angular:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name : angular-container
    volumes:
     - C:\Users\Ebrahim\Desktop\jenkins\workspace\angular-pipeline:/usr/src/app
    ports:
      - "4200:4200"