version: '3'

services:
 angular:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-build
    restart: unless-stopped
    volumes:
     - /var/jenkins_home/workspace/angular-pipeline:/usr/src/app
   